baseURL = "http://bakalesoftware.netlify.app/"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "Bakales Software"
[markup.goldmark.renderer]
unsafe = true
