[de]
contentDir = "content/deutsch"
copyright = "Copyright ©2021 by Bakales Software. All Right Reserved"
footer_content = "राहकों की संतुष्टि हमारी प्रमुख प्राथमिकता है। निम्नलिखित सोशल मीडिया से जुड़ें।"
footer_menu_left = "Firma"
footer_menu_middle = "Produkte"
footer_menu_right = "Support"
languageName = "Hi"
title = "Bakales Software"
weight = 2
[en]
contentDir = "content/english"
copyright = "Copyright ©2021 by Bakales Software. All Right Reserved"
footer_content = "Customer satisfaction is our prime priority. Connect us with the following social media."
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
languageName = "En"
title = "Bakales Software"
weight = 1
