[[footer_left]]
name = "मूल्य निर्धारण"
url = "pricing"
[[footer_middle]]
name = "विशेषताएं"
url = "#"
[[footer_right]]
name = "गोपनीयता नीति"
url = "privacy-policy"
[[footer_right]]
name = "नियम एवं शर्तें"
url = "terms-conditions"
[[footer_right]]
name = "सामान्य प्रश्न"
url = "faq"
[[main]]
name = "घर"
url = "/"
weight = 1
[[main]]
name = "मूल्य निर्धारण"
url = "pricing"
weight = 3
[[main]]
name = "संपर्क करें"
url = "https://forms.gle/odKVVx4rkfeJvfy5A"
weight = 4
[[main]]
name = "सामान्य प्रश्न"
url = "faq"
weight = 5
