[[footer_left]]
name = "Pricing"
url = "pricing"
[[footer_middle]]
name = "Features"
url = "#"
[[footer_right]]
name = "Privacy Policy"
url = "privacy-policy"
[[footer_right]]
name = "Terms & Conditions"
url = "terms-conditions"
[[footer_right]]
name = "FAQ"
url = "faq"
[[main]]
name = "Home"
url = "/"
weight = 1
[[main]]
name = "Pricing"
url = "pricing"
weight = 3
[[main]]
name = "Contact"
url = "https://forms.gle/odKVVx4rkfeJvfy5A"
weight = 4
[[main]]
name = "FAQ"
url = "faq"
weight = 5
