[[footer_left]]
name = "हमारे बारे में"
url = "#"
[[footer_left]]
name = "जल्दी शुरू"
url = "#"
[[footer_left]]
name = "मूल्य निर्धारण"
url = "pricing"
[[footer_middle]]
name = "Pricing"
url = "pricing"
[[footer_middle]]
name = "Platform"
url = "#"
[[footer_middle]]
name = "Features"
url = "#"
[[footer_right]]
name = "Privacy Policy"
url = "privacy-policy"
[[footer_right]]
name = "Terms & Conditions"
url = "terms-conditions"
[[footer_right]]
name = "FAQ"
url = "faq"
[[main]]
name = "घर"
url = "/"
weight = 1
[[main]]
name = "मूल्य निर्धारण"
url = "pricing"
weight = 3
[[main]]
name = "संपर्क करें"
url = "contact"
weight = 4
[[main]]
name = "सामान्य प्रश्न"
url = "faq"
weight = 5
